In try-catch block when an error is logged or a new exception is throw, there are at least two mandatory pieces of information that must be provided:

* Some contextual information to make it easy in production environment to quickly know what was the context when the error occurred and so potentially to easily reproduce and fix the bug in a non-production environment.
* The stack of exceptions to know exactly where the unexpected conditions happened

The following code snippet illustrates this rule:

{code}
try {...} catch(Exception e) { log.info("Here is the context"); }   //Non-Compliant, the error stack-trace is missing
try {...} catch(Exception e) { log.error(myContext, e);  }            //Compliant
try {...} catch(Exception e) {
  String message = "...."
  throw new BusinessException(message, e);                          //Compliant
}
try {...} catch(Exception e) { logger.error(e); }                           //Non-Compliant, the context is missing
try {...} catch(Exception e) { logger.warning(e.getMessage()); } //Non-Compliant, the stack-trace is missing
try {...} catch(Exception e) {
  String message = "....";
  throw new BusinessException(message);                          //Non-Compliant, the original exception is missing
}
try {...} catch(Exception e) {
  String message = "....";
  log.debug(message);                                                             //Compliant as in the next statement the original exception is preserved
  throw new BusinessException(message, e);                          //Compliant, the original exception is preserved
}
{code}
